listen:
  type: port
  bind_ip: 0.0.0.0
  port: 4444
mongodb:
  host: mongo
  port: 27017
  database: user-service
  auth_db: admin
  username: root
  password: qwerty
  collection: users
secret:
  jwtkey: golang